<script setup>
import SocialsCarousel from '@/components/SocialsCarousel.vue'
</script>

<template>
    <footer>
        <div id="socials">
            <h3>Contact</h3>
            <SocialsCarousel :socials="[
                {
                    name: 'Github',
                    src: '/src/assets/img/socials/github.png',
                    href: 'https://github.com/marcosggdev'
                },
                {
                    name: 'LinkedIn',
                    src: '/src/assets/img/socials/linkedin.png',
                    href: 'https://www.linkedin.com/in/marcos-garcia-garcia-dev/'
                },
                {
                    name: 'Gmail',
                    src: '/src/assets/img/socials/gmail.png',
                    href: 'mailto:marcosggdev@gmail.com'
                },
            ]" />
        </div>
        <div id="mentions">
            <h3>Mentions</h3>
            <SocialsCarousel :socials="[
                {
                    name: 'IBQ',
                    src: '/src/assets/img/socials/ibq.jpg',
                    href: 'https://ibq.es/'
                },
                {
                    name: 'Uniovi',
                    src: '/src/assets/img/socials/uniovi.jpg',
                    href: 'https://ciencias.uniovi.es/'
                },
            ]" />
        </div>
        <div id="credits">
            <h3>Credits</h3>
            <small>All the images used in this page are of free use or have been generated by Microsoft Designers AI</small>
            <div class="image-container">
                <img src="@/assets/img/microsoft_designer_1.jpg" alt="">
                <img src="@/assets/img/microsoft_designer_2.jpg" alt="">
            </div>
        </div>
        <small class="copy">&copy; All rights reserved. Marcos García García</small>
    </footer>
</template>

<style scoped>
footer {
    background-color: var(--primary);
    padding: 2em;
    min-height: 50vh;
    color: var(--light);
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: auto 20px;
    align-items: flex-start;
    justify-content: space-between;
}
footer .copy {
    grid-column: 2 / 3;
    display: flex;
    justify-content: center;
}
footer a {
    color: var(--light);
}
footer #credits img {
    width: 100%;
    height: auto;
    border-radius: 20px;
    transform: scale(0.8) rotateZ(5deg);
}
footer #credits .image-container {
    display: flex;
    align-items: center;
    position: relative;
}

footer #credits .image-container img:last-child {
    position: absolute;
    left: 39%;
    top: 28%;
    transform: scale(0.5) rotateZ(-10deg);
}
</style>