<script setup>
import SocialsCarousel from '@/components/SocialsCarousel.vue'
</script>

<template>
    <footer>
        <div id="socials">
            <section id="contact">
                <div class="title">
                    <h3>Contact</h3>
                </div>
                <div class="content">
                    <SocialsCarousel :socials="[
                        {
                            name: 'Github',
                            src: '/src/assets/img/socials/github.png',
                            href: 'https://github.com/marcosggdev'
                        },
                        {
                            name: 'LinkedIn',
                            src: '/src/assets/img/socials/linkedin.png',
                            href: 'https://www.linkedin.com/in/marcos-garcia-garcia-dev/'
                        },
                        {
                            name: 'Gmail',
                            src: '/src/assets/img/socials/gmail.png',
                            href: 'mailto:marcosggdev@gmail.com'
                        },
                    ]" />
                </div>
            </section>
            <section id="poweredBy">
                <div class="title">
                    <h3>Powered by</h3>
                </div>
                <div class="content">
                    <ul>
                        <li><img class="md-icon" src="@/assets/img/icons/html.png" alt=""></li>
                        <li><img class="md-icon" src="@/assets/img/icons/css.png" alt=""></li>
                        <li><img class="md-icon" src="@/assets/img/icons/js.png" alt=""></li>
                        <li><img class="md-icon" src="@/assets/img/icons/vuejs.png" alt=""></li>
                        <li><img class="md-icon" src="@/assets/img/icons/nodejs.png" alt=""></li>
                    </ul>
                </div>
            </section>
        </div>
        <div id="mentions">
            <h3>Mentions</h3>
            <SocialsCarousel :socials="[
                        {
                            name: 'IBQ',
                            src: '/src/assets/img/socials/ibq.jpg',
                            href: 'https://ibq.es/'
                        },
                        {
                            name: 'Uniovi',
                            src: '/src/assets/img/socials/uniovi.jpg',
                            href: 'https://ciencias.uniovi.es/'
                        },
                    ]" />
            <p>Have a look at this resources. Its a very good approach to start programming graphic applications</p>
            <ul>
                <li><a class="social-link" href="https://webglfundamentals.org/"><img class="md-icon"
                            src="@/assets/img/icons/website.png" alt="">WebGL Fundamentals</a></li>
                <li><a class="social-link"
                        href="https://www.amazon.com/Computer-Graphics-Programming-OpenGL-Second-ebook/dp/B07HNF4YSN"><img
                            class="md-icon" src="@/assets/img/icons/book.png" alt="">Computer Graphics Programming in OpenGL with Java</a></li>
            </ul>
        </div>
        <div id="credits">
            <h3>Credits</h3>
            <small>All the images used in this page are of free use or have been generated by Microsoft Designers
                AI</small>
            <div class="image-container">
                <img src="@/assets/img/microsoft_designer_1.jpg" alt="">
                <img src="@/assets/img/microsoft_designer_2.jpg" alt="">
            </div>
        </div>
        <small class="copy">&copy; All rights reserved. Marcos García García</small>
    </footer>
</template>

<style scoped>
footer {
    background-color: var(--primary);
    min-height: 50vh;
    color: var(--light);
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: auto auto;
    align-items: flex-start;
    justify-content: space-between;
}

footer>div {
    padding: 4em;
}

footer .copy {
    grid-column: 2 / 4;
    display: flex;
    justify-content: center;
    padding: 1em;
    box-sizing: border-box;
    background-color: var(--dark-darker);
}

footer a {
    color: var(--light);
}

footer #credits img {
    width: 100%;
    height: auto;
    border-radius: 20px;
    transform: scale(0.8) rotateZ(5deg);
}

footer #credits .image-container {
    display: flex;
    align-items: center;
    position: relative;
}

footer #credits .image-container img:last-child {
    position: absolute;
    left: 39%;
    top: 28%;
    transform: scale(0.5) rotateZ(-10deg);
}

#socials {
    grid-row: 1 / 3;
    height: 100%;
    border-radius: 20px;
    transform: scale(1.1) rotateZ(357deg);
    color: var(--dark);
    padding: 0;
}

#socials>section {
    box-sizing: border-box;
}

#socials>section .title {
    padding: 2em;
}

#socials>section h3 {
    padding: 0;
}

#socials>section .content {
    padding: 1em;
    display: flex;
    flex-direction: column;
    align-items: center;
    overflow: hidden;
}
#contact, #poweredBy {
    color: white;
    background: linear-gradient(40deg, #9280c2, #2d2d2d);
}
#contact {
    border-radius: 0px 20px 20px 0px;
    filter: drop-shadow(2px 2px 5px black);
}
#contact ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    align-items: center;
    gap: 10px;
    justify-content: center;
}

#contact ul li a span {
    color: black;
}

#contact ul li {
    gap: 10px;
    display: flex;
    align-items: center;
}

#poweredBy {
    height: 100%;
    filter: drop-shadow(0px 4px 4px black);
    border-radius: 20px;
    transform: scale(1.05) rotateZ(4deg);
}
#poweredBy ul li img {
    transition: all 0.25s;
    padding: 10px;
}
#poweredBy ul li img:hover {
    transform: scale(1.1) rotateZ(5deg);
    border-radius: 10px;
    background-color: var(--light);
}
#mentions {
    border-radius: 0px 0px 20px 0px;
    background-color: rebeccapurple;
}
#mentions ul:last-child {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
}
#credits {
    display: flex;
    flex-direction: column;
    align-items: center;
    height: 100%;
    background-color: var(--dark-darker);
}
</style>